# Generated by Django 5.0.1 on 2024-01-19 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_user_property_user_rename_user_rental_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='User',
            new_name='user',
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.folder')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.property')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
